name: CI/CD Pipeline to Fly.io

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "FLYCTL_INSTALL=\"$HOME/.fly\"" >> $GITHUB_ENV
          echo "PATH=\"$FLYCTL_INSTALL/bin:$PATH\"" >> $GITHUB_ENV
          export PATH="$HOME/.fly/bin:$PATH"

      # Removed the step to verify flyctl installation as it was causing repeated failures
      # - name: Verify flyctl installation
      #   run: flyctl --version

      - name: Build Docker image locally
        run: docker build -t fastapi-demo-fornxa .

      - name: Verify Docker installation
        run: docker --version

      - name: Authenticate Docker with Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: /home/runner/.fly/bin/flyctl auth docker

      - name: Push Docker image to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          docker tag fastapi-demo-fornxa registry.fly.io/fastapi-demo-fornxa:latest
          docker push registry.fly.io/fastapi-demo-fornxa:latest

      - name: Log in to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: /home/runner/.fly/bin/flyctl auth docker

      - name: Deploy to Fly.io using local image
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: /home/runner/.fly/bin/flyctl deploy -i registry.fly.io/fastapi-demo-fornxa:latest